import '../sass/_global.scss';
import { Exo } from 'next/font/google';
import Provider from '@/app/context/AuthContext';
import ToasterContext from './context/ToasterContext';
import Navbar from '@/app/components/Navigation/Navbar';

// * Getting the url here and render the navbar according

const inter = Exo({
  weight: ['100', '200', '300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <header>
            <Navbar />
          </header>
          <ToasterContext />
          {children}
        </Provider>
      </body>
    </html>
  );
}
